version: "3.8"

services:

  books-pyapi:
    build: .
    image: books-pyapi
    container_name: books-pyapi
    ports:
      - "9000:9000"
    environment:
      DB_TYPE: sqlite
      DB_PATH: /database/books.db
    volumes:
      - .:/database
    healthcheck:
      test: ["CMD", "ash", "-c", 
        "curl -fsSL -X 'GET' 'http://localhost:9000/api/v1/health' -H 'accept: application/json'"]
      interval: 30s
      timeout: 5s
      retries: 3

  # Populate database with some data through the API
  # Comment the block below if you want to start with a empty database
  database-init:
    image: books-pyapi
    container_name: database-init
    entrypoint: ash
    command: "/extras/populate.sh"
    environment:
      SERVER: books-pyapi
    volumes:
      - ./extras/populate.sh:/extras/populate.sh
    depends_on: 
      books-pyapi:
        condition: service_healthy
