name: Terraform - Lint & Drift Detection

on: [push]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

jobs:

  lint:
    name: Terraform Lint and Validate
    runs-on: ubuntu-22.04
    defaults:
        run:
          working-directory: infra/ecs

    steps:
    - uses: actions/checkout@v3
    

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.8

    - name: Terraform init
      run: terraform init -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}" -backend-config="dynamodb_table=${{ vars.TF_STATE_BUCKET }}"
    
    - name: Terraform FMT
      run: terraform fmt --recursive -check
      working-directory: infra
    
    - name: Terraform Validate
      run: terraform validate
    

  plan:
    name: Terraform Plan
    needs: lint
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: infra/ecs

    steps:
    - uses: actions/checkout@v3
    

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.8

    - name: Terraform init
      run: terraform init -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}" -backend-config="dynamodb_table=${{ vars.TF_STATE_BUCKET }}"
    
    - name: Terraform Plan
      run: terraform plan -no-color -input=false | tee terraform.plan
      continue-on-error: true

    - name: Check Drift
      run: |
        grep "No changes. Your infrastructure matches the configuration." terraform.plan || \
        (printf "\n ⚠️ \033[0;31mDrift detected in the infrastructure, please check the step \033[0;32m'Terraform Plan' \033[0;31m!\033[0m" ; exit 1)
